language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install --upgrade pip
  - pip install virtualenv
  - virtualenv ~/jepvenv
  - source ~/jepvenv/bin/activate
  - pip install pytest-cov coveralls
  - pip install .
  - pip list
script:
  - python setup.py test -a "--cov=jep_py"
  - jep-cmake -h
after_success:
  - coveralls